Add date conditionals #181
ClubObsidian/DynamicGui pull request #221
Opened 2022-02-01 03:24 UTC by njsharpe

Date & time format can be changed to any format. This is just what I chose. Check commented lines on date parse fail - good first issue.

2022-02-01 03:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ClubObsidian/DynamicGui?pullRequest=221) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ClubObsidian/DynamicGui?pullRequest=221) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ClubObsidian/DynamicGui?pullRequest=221) it.</sub>

2022-02-01 08:08 UTC, virustotalop reviewed
Looks good overall, just have a few changes and then it looks good to go.

2022-02-01 08:08 UTC, virustotalop commented on core/src/main/java/com/clubobsidian/dynamicgui/function/impl/condition/AfterDateLazyFunction.java
> +            return ConditionFunction.ZERO;
Just log the params with something along the lines of `Invalid date <data>`, then it can just fall through to the last return.

2022-02-01 08:08 UTC, virustotalop commented on core/src/main/java/com/clubobsidian/dynamicgui/function/impl/condition/BeforeDateLazyFunction.java
> +            // Log here? Throw?
Same thing as the other function

2022-02-01 08:08 UTC, virustotalop commented on core/src/main/java/com/clubobsidian/dynamicgui/function/impl/condition/AfterDateLazyFunction.java
> +        super("AFTRDATE", 1, true);
AFTERDATE would be preferred

2022-02-01 08:08 UTC, virustotalop commented on core/src/main/java/com/clubobsidian/dynamicgui/function/impl/condition/BeforeDateLazyFunction.java
> +        super("BFRDATE", 1, true);
BEFOREDATE would be preferred

2022-02-01 08:16 UTC, virustotalop requested changes

2022-02-01 08:16 UTC, virustotalop commented on core/src/main/java/com/clubobsidian/dynamicgui/function/impl/condition/AfterDateLazyFunction.java
> +            Date expected = new SimpleDateFormat("MM dd, yyyy HH:mm:ss").parse(lazyParams.get(0).getString());
The date time format should probably be configurable, config values can be loaded here.
https://github.com/ClubObsidian/DynamicGui/blob/master/core/src/main/java/com/clubobsidian/dynamicgui/DynamicGui.java#L192

2022-02-01 08:16 UTC, virustotalop commented on core/src/main/java/com/clubobsidian/dynamicgui/function/impl/condition/BeforeDateLazyFunction.java
> +            Date expected = new SimpleDateFormat("MM dd, yyyy HH:mm:ss").parse(lazyParams.get(0).getString());
Here as well

2022-02-02 01:33 UTC, njsharpe commented
Completed requested changes + bug fix.

2022-02-02 01:40 UTC, virustotalop approved these changes

2022-02-02 01:40 UTC, merged

2022-02-02 01:40 UTC, virustotalop commented
Everything looks good, thank you for the pull request.